name: CI

on:
  workflow_dispatch:
  push:
    branches: [ 'master' ]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: EzXHepler-QSlock
          path: app/build/outputs

      - name: Set ci tag
        run: git tag -f ci; git push -f --tags

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "app/build/outputs/apk/release/*.apk"
          name: "CI Build"
          omitBody: true
          omitBodyDuringUpdate: true
          tag: ci
